export const ADD_PRODUCT_CARD = "ADD_PRODUCT_CARD";
export const GET_NUMBERS_IN_CARD = "GET_NUMBERS_IN_CARD";
export const CHECK_TOKEN = "CHECK_TOKEN";

//Sign Up
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_ERROR = "SIGNUP_ERROR";
//Sign In
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNIN_ERROR = "SIGNIN_ERROR";
//Sign out
export const SIGNOUT_SUCCESS = "SIGNOUT_SUCCESS";
export const SIGNOUT_ERROR = "SIGNOUT_ERROR";
