//Produit action
export const FETCH_PRODUIT_REQUEST = "FETCH_PRODUIT_REQUEST";
export const FETCH_PRODUIT_SUCCES = "FETCH_PRODUIT_SUCCES";
export const FETCH_PRODUIT_FAILURE = "FETCH_PRODUIT_FAILURE";

//Card action
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_ITEM = "REMOVE_ITEM";
export const SUB_QUANTITY = "SUB_QUANTITY";
export const ADD_QUANTITY = "ADD_QUANTITY";
export const ADD_SHIPPING = "ADD_SHIPPING";

export const ADD_PRODUCT_CARD = "ADD_PRODUCT_CARD";
export const GET_NUMBERS_IN_CARD = "GET_NUMBERS_IN_CARD";
export const CHECK_TOKEN = "CHECK_TOKEN";

//Sign Up
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_ERROR = "SIGNUP_ERROR";
//Sign In
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNIN_ERROR = "SIGNIN_ERROR";
//Sign out
export const SIGNOUT_SUCCESS = "SIGNOUT_SUCCESS";
export const SIGNOUT_ERROR = "SIGNOUT_ERROR";

//
export const authTypes = {
  SET_CURRENT_USER: "SET_CURRENT_USER",
  CLEAR_CURRENT_USER: "CLEAR_CURRENT_USER"
};
